config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  get 'signin' => 'sessions#new'
  post 'signin' => 'sessions#create'
  delete 'signout' => 'sessions#destroy'

  resources :users
  resources :favorite_users, only: :index
  post 'favorite_user' => 'favorite_users#toggle'

  resources :reports do
    resources :comments, only: %i(create edit update destroy)
    get 'latest_report' => 'reports#latest_report'
  end
  resources :my_reports, only: %i(index)
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :report
  belongs_to :user
end

app/models/favorite_user_relation.rb
class FavoriteUserRelation < ActiveRecord::Base
  belongs_to :from, class_name: 'User', foreign_key: :from_id
  belongs_to :to, class_name: 'User', foreign_key: :to_id
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy

  def previous
    Report.where('id < ?', self.id).order(created_at: :desc, id: :desc).first
  end

  def next
    Report.where('id > ?', self.id).order(created_at: :desc, id: :desc).reverse.first
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  before_create :create_remember_token

  has_many :favorite_user_relations, foreign_key: :from_id
  has_many :favorite_users, through: :favorite_user_relations, source: :to
  has_many :reports, dependent: :destroy

  def self.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def self.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include SessionsHelper

  before_action :signin_required

  private

  def redirect_back_or(default)
    redirect_to(session[:request_from] || default)
    session[:request_from] = nil
  end

  def signin_required
    return if signed_in?
    set_request_from
    redirect_to signin_path
  end

  def set_request_from
    session[:request_from] = request.fullpath
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_report
  before_action :set_comment, only: %i(edit update destroy)

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to report_path(@comment.report_id), notice: '作成しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to report_path(@comment.report_id), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    redirect_to report_path(@comment.report), notice: '削除しました'
  end

  private

  def set_report
    @report = Report.find(params[:report_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:report_id, :user_id, :description)
  end
end

app/controllers/favorite_users_controller.rb
class FavoriteUsersController < ApplicationController
  before_action :set_user, only: :toggle

  def index
    @favorite_reports = Report.where(user: current_user.favorite_users).page(params[:page]).order(:id)
  end

  def toggle
    pair = { from: current_user, to: @user }
    if current_user.favorite_user_relations.exists?(pair)
      current_user.favorite_user_relations.find_by(pair).destroy
    else
      current_user.favorite_user_relations.create(pair)
    end
    redirect_to :back
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/my_reports_controller.rb
class MyReportsController < ApplicationController
  def index
    @my_reports = Report.where(user: current_user).page(params[:page]).order(created_at: :desc)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i(show edit update destroy)

  def index
    @reports = Report.page(params[:page]).order(created_at: :desc)
  end

  def show
    @comment = Comment.new
    @reports = Report.all
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params)
    if @report.save
      redirect_to @report, notice: '作成しました'
    else
      render :new
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @report.destroy
    redirect_to reports_url, notice: '削除しました'
  end

  def latest_report
    @latest_report = Report.where(user: current_user).order(:created_at).last
    if @latest_report
      render json: @latest_report and return if request.xhr?
    else
      render json: Report.new and return request.xhr?
    end
  end

  private

  def set_report
    @report = Report.find(params[:id])
  end

  def report_params
    params.require(:report).permit(:user_id, :place, :overwork, :work, :probrem, :solution, :plan, :other)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :signin_required

  def new
    redirect_to root_path if signed_in?
  end

  def create
    user = User.find_by(signin_id: session_params[:signin_id])
    if authenticated?(user)
      signin user
      redirect_back_or(root_path)
    else
      flash.now[:alert] = t('message_invalid_signin')
      render action: :new
    end
  end

  def destroy
    signout
    redirect_to signin_path
  end

  private

  def session_params
    params.require(:session).permit(:signin_id, :password)
  end

  def authenticated?(user)
    user && user.authenticate(session_params[:password])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i(show edit update destroy)

  def index
    @users = User.page(params[:page]).order(:id)
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: '作成しました'
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to users_path, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: '削除しました'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:signin_id, :password, :password_confirmation, :name, :admin)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @reports = Report.page(params[:page]).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def name_with_comment_count(report)
    report.comments.present? ? "#{report.user.name} (#{report.comments.count})" : report.user.name
  end
  
  def created_at_with_comment_count(report)
    l(report.created_at, format: :report) + render_comment_count(report)
  end

  def render_comment_count(report)
    " (#{report.comments.count})"
  end

  def page_title(title)
    title.blank? ? WeeklyReport::Application.config.title : "#{title} | #{WeeklyReport::Application.config.title}"
  end

  def all_day_of_week_ago(value)
    from = (Date.today - value.week).beginning_of_week.beginning_of_day
    to = (from + 6.day).end_of_day
    from..to
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def favorite?
    FavoriteUserRelation.exists?(from: current_user, to: @report.user)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signin(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    session[:user_id] = user.id
  end

  def signed_in?
    session[:user_id].present?
  end

  def signout
    session[:user_id] = nil
    cookies.delete(:remember_token)
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @cached_current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end
end

app/views/comments/_index.html.slim
- if current_user or @comments.present?
    hr
- @report.comments.each do |comment|
  p = l comment.created_at, format: :comment
  p = comment.user.name
  p = comment.description
  - if comment.user == current_user
    .pull-right
      = link_to '編集', edit_report_comment_path(@report, comment), class: 'btn btn-link'
      '|
      = link_to '削除', report_comment_path(@report, comment), data: { confirm: '本当に削除しますか?' }, method: :delete, class: 'btn btn-link'
    .clearfix
  hr

app/views/comments/_new.html.slim
= form_for @comment, url: report_comments_path(@report) do |f|
  = f.hidden_field :report_id, value: @report.id
  = f.hidden_field :user_id, value: current_user&.id

  .form-group
    = f.text_area :description, class: 'form-control', rows: 5, placeholder: 'コメント'

  .actions.pull-right
    = f.submit 'コメントする', class: 'btn btn-default'

app/views/comments/edit.html.slim
- provide :title, t('title_comment_edit')
= form_for [@report, @comment] do |f|
  = f.hidden_field :report_id, value: @report.id
  = f.hidden_field :user_id, value: current_user&.id

  .form-group
    = f.text_area :description, class: 'form-control', rows: 5, placeholder: 'コメント'

  .actions.pull-right
    = f.submit '送信', class: 'btn btn-default'

app/views/favorite_users/index.html.slim
- provide :title, t('title_favorite_user_index')
h1 お気に入りユーザー 一覧

- if @favorite_reports.present?
  - 3.times do |value|
    - days = all_day_of_week_ago(value)
    h1 = "#{l(days.first, format: :report)} - #{l(days.last, format: :report)}"

    table.table.table-hover.table-condensed
      tbody
        - @favorite_reports.where(created_at: all_day_of_week_ago(value)).each do |report|
          tr
            td = link_to name_with_comment_count(report), report, class: 'btn btn-link'
- else
  p お気に入りユーザーは登録されていません

br
= paginate @favorite_reports

app/views/layouts/application.html.slim
doctype html
html
  head
    title = page_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      nav.navbar.navbar-default
        .container
          .navbar-header
            = link_to WeeklyReport::Application.config.title, root_path, class: 'navbar-brand'

            ul.nav.navbar-nav
              li = link_to '週報一覧', reports_path, class: 'btn btn-link'
              li = link_to 'お気に入りユーザー 一覧', favorite_users_path, class: 'btn btn-link'
              li = link_to 'my週報 一覧', my_reports_path, class: 'btn btn-link'
              - if current_user&.admin?
                li = link_to 'ユーザー一覧', users_path, class: 'btn btn-link'

          - if signed_in?
            ul.nav.navbar-nav.navbar-right
              li = link_to t(:label_signout), signout_path, method: :delete, class: 'glyphicon glyphicon-log-out'

    .container
      - flash.each do |name, msg|
        div class="alert alert-#{ name.to_s == 'notice' ? 'success' : 'danger' }"
          button.close type='button' data-dismiss='alert' aria-hidden='true' x
          = content_tag :div, msg, id: "flash_#{name}"

      == yield

app/views/my_reports/index.html.slim
- provide :title, t('title_my_report_index')

h1 my週報 一覧

table.table.table-hover.table-condensed
  tbody
    - @my_reports.each do |report|
      tr
        td = link_to created_at_with_comment_count(report), report, class: 'btn btn-link'

br
= link_to '新規作成', new_report_path, class: 'btn btn-default'
br
= paginate @my_reports

app/views/reports/_form.html.slim
= link_to '最新の週報内容', '#', id: 'latest_report_button', class: 'btn btn-default pull-right'
.clearfix
br

.form-horizontal
  = form_for @report do |f|
    = f.hidden_field :user_id, value: current_user&.id

    .form-group
      = f.label :place, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :place, class: 'form-control', rows: '3'

    .form-group
      = f.label :overwork, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.number_field :overwork, class: 'form-control'

    .form-group
      = f.label :work, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :work, class: 'form-control', rows: '6'

    .form-group
      = f.label :probrem, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :probrem, class: 'form-control', rows: '6'

    .form-group
      = f.label :solution, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :solution, class: 'form-control', rows: '6'

    .form-group
      = f.label :plan, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :plan, class: 'form-control', rows: '6'

    .form-group
      = f.label :other, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_area :other, class: 'form-control', rows: '6'

    .actions
      .col-sm-offset-2
        = f.submit '送信', class: 'btn btn-default'

javascript:
  document.getElementById('report_place').focus();

app/views/reports/edit.html.slim
- provide :title, t('title_report_edit')
== render 'form'

app/views/reports/index.html.slim
- provide :title, t('title_report_index')

- 3.times do |value|
  - days = all_day_of_week_ago(value)
  h1 = "#{l(days.first, format: :report)} - #{l(days.last, format: :report)}"

  table.table.table-hover.table-condensed
    tbody
      - @reports.where(created_at: all_day_of_week_ago(value)).each do |report|
        tr
          td = link_to name_with_comment_count(report), report, class: 'btn btn-link'

  - if value == 0
    br
    = link_to '新規作成', new_report_path, class: 'btn btn-default'

br
= paginate @reports

app/views/reports/new.html.slim
- provide :title, t('title_report_new')
== render 'form'

app/views/reports/show.html.slim
- provide :title, @report.user.name
p#notice = notice

.pull-left
  - unless @report == @reports.first
    = link_to '前へ', @report.previous
.pull-right
  - unless @report == @reports.last
    = link_to '次へ', @report.next
.clearfix

.panel.panel-default
  .panel-heading
    h3.panel-title
      = @report.user.name
      = link_to favorite? ? '★' : '☆', favorite_user_path(user_id: @report.user.id), method: :post

  .panel-body
    dl.dl-horizontal
      dt = t 'activerecord.attributes.report.place'
      dd = simple_format @report.place
      hr

      dt = t 'activerecord.attributes.report.overwork'
      dd = @report.overwork
      hr

      dt = t 'activerecord.attributes.report.work'
      dd = simple_format @report.work
      hr

      dt = t 'activerecord.attributes.report.probrem'
      dd = simple_format @report.probrem
      hr

      dt = t 'activerecord.attributes.report.solution'
      dd = simple_format @report.solution
      hr

      dt = t 'activerecord.attributes.report.plan'
      dd = simple_format @report.plan
      hr

      dt = t 'activerecord.attributes.report.other'
      dd = simple_format @report.other

.pull-right
  - if current_user?(@report.user)
    = link_to '編集', edit_report_path(@report), class: 'btn btn-link'
.clearfix

== render 'comments/index'

== render 'comments/new'

app/views/users/_form.html.slim
.form-horizontal
  = form_for @user do |f|
    - if @user.errors.any?
      #error_explanation
        h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        ul
          - @user.errors.full_messages.each do |message|
            li = message

    .form-group
      = f.label :signin_id, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :signin_id, class: 'form-control'

    .form-group
      = f.label :password, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :password, class: 'form-control'

    .form-group
      = f.label :password_confirmation, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :password_confirmation, class: 'form-control'

    .form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control'

    .form-group
      = f.label :admin, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.check_box :admin, class: 'form-control'

    .actions
      .col-sm-offset-2
        = f.submit '送信', class: 'btn btn-default'

app/views/users/edit.html.slim
- provide :title, t('title_user_edit')
== render 'form'

app/views/users/index.html.slim
- provide :title, t('title_user_index')
h1 ユーザー 一覧

table.table.table-hover
    thead
      tr
        th = t('activerecord.attributes.user.signin_id')
        th = t('activerecord.attributes.user.name')
        th = t('activerecord.attributes.user.admin')
        th
        th

    tbody
      - @users.each do |user|
          tr
            td = user.signin_id
            td = link_to user.name, user
            td = user.admin
            td = link_to '編集', edit_user_path(user)
            td = link_to '削除', user, data: {:confirm => '本当に削除しますか？'}, :method => :delete

br
= link_to '新規作成', new_user_path, class: 'btn btn-default'
br
= paginate @users

app/views/users/new.html.slim
- provide :title, t('title_user_new')
== render 'form'

app/views/users/show.html.slim
- provide :title, @user.name

.panel.panel-default
  .panel-heading
    h3.panel-title
      = @user.name

  .panel-body
    dl.dl-horizontal
      dt = t 'activerecord.attributes.user.signin_id'
      dd = @user.signin_id
      hr

      dt = t 'activerecord.attributes.user.admin'
      dd = @user.admin

.pull-right
  = link_to '編集', edit_user_path(@user)

app/views/welcome/index.html.slim
- 3.times do |value|
  - days = all_day_of_week_ago(value)
  h1 = "#{l(days.first, format: :report)} - #{l(days.last, format: :report)}"

  table.table.table-hover.table-condensed
    tbody
      - @reports.where(created_at: all_day_of_week_ago(value)).each do |report|
        tr
          td = link_to name_with_comment_count(report), report, class: 'btn btn-link'

  - if value == 0
    br
    = link_to '新規作成', new_report_path, class: 'btn btn-default'

br
= paginate @reports